version: '3'
services:
  node:
    build: .
    container_name: node-app
    ports:
      - "3001:3000"
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
  
    networks:
      - my-network

networks:
  my-network:
